# 站点配置
title: znlgis 博客
description: GIS开发与技术分享
author: znlgis
baseurl: ""
url: "https://znlgis.github.io"

# 主题配置
markdown: kramdown
highlighter: rouge

# 排除文件
exclude:
  - README.md
  - LICENSE
  - .gitignore
  - gis/basic/pom

# 集合配置
collections:
  posts:
    output: true
    permalink: /:title/

# 默认值
defaults:
  - scope:
      path: ""
    values:
      layout: default
